# 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [1]:
import pandas as pd
import pathlib as pl
cartella = pl.Path(r"C:\Users\peter_6\Downloads\trendingYT\trendingYT")
df = pd.concat((pd.read_csv(f, encoding="latin1").assign(country=f.stem[:2]) 
     for f in cartella.glob("*.csv")), ignore_index=True)
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. BeyoncÃ©,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. BeyoncÃ© ...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO â¶ \n\nSUBSCRIBE âº ...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,ð§: https://ad.gt/yt-perfect\nð°: https://...,CA

In [2]:
df.shape

(375942, 17)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375942 entries, 0 to 375941
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   video_id                375942 non-null  object
 1   trending_date           375942 non-null  object
 2   title                   375942 non-null  object
 3   channel_title           375942 non-null  object
 4   category_id             375942 non-null  int64
 5   publish_time            375942 non-null  object
 6   tags                    375942 non-null  object
 7   views                   375942 non-null  int64
 8   likes                   375942 non-null  int64
 9   dislikes                375942 non-null  int64
 10  comment_count           375942 non-null  int64
 11  thumbnail_link          375942 non-null  object
 12  comments_disabled       375942 non-null  bool
 13  ratings_disabled        375942 non-null  bool
 14  video_error_or_removed  375942 non-null  bool
 15  description             356464 non-null  object
 16  country                 375942 non-null  object
dtypes: bool(3), int64(5), object(9)
memory usage: 41.2+ MB

# 2. Extract all videos that have no tag.

In [4]:
no_tags = df[df['tags'] == '[none]']
no_tags

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
41,JwboxqDylgg,17.14.11,Canada Soccer's Women's National Team v USA In...,Canada Soccer,17,2017-11-13T05:53:49.000Z,[none],36311,277,28,13,https://i.ytimg.com/vi/JwboxqDylgg/default.jpg,False,False,False,Canada Soccer's Women's National Team face riv...,CA
58,9B-q8h31Bpk,17.14.11,John Oliver Tackles Louis C.K. And Donald Trum...,TV Shows,22,2017-11-13T04:49:26.000Z,[none],106029,1270,101,181,https://i.ytimg.com/vi/9B-q8h31Bpk/default.jpg,False,False,False,"John Oliver on News, Politics ...",CA
78,1UE5Dq1rvUA,17.14.11,Taylor Swift Perform Ready For It - SNL,Ken Reactz,24,2017-11-12T05:18:02.000Z,[none],320964,8069,285,717,https://i.ytimg.com/vi/1UE5Dq1rvUA/default.jpg,False,False,False,Thanks for watching please subscribe and subsc...,CA
86,pmJQ4KwliX4,17.14.11,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",James Munder,2,2017-11-12T21:25:40.000Z,[none],116820,1503,139,1066,https://i.ytimg.com/vi/pmJQ4KwliX4/default.jpg,False,False,False,https://pastebin.ca/3930472\n\nSupport My Chan...,CA
98,lHcXhBojpeQ,17.14.11,ä¸å±TVBè¦å¸ï¼ææ£10å¹´éæ¢ ç«¹é¦¬é«®å¦...,ææç¾æç,22,2017-11-12T12:49:50.000Z,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375815,VGykknw9eCM,18.14.06,"Made Defiant: The Mixtape ft. Neymar Jr., Kane...",Beats by Dre,10,2018-06-07T07:01:06.000Z,[none],3577614,12318,1345,1414,https://i.ytimg.com/vi/VGykknw9eCM/default.jpg,False,False,False,"When your time comes, you have two choices. Yo...",US
375819,fAIX12F6958,18.14.06,Bumblebee (2018) - Official Teaser Trailer - P...,Paramount Pictures,1,2018-06-05T07:00:01.000Z,[none],19864779,228670,16420,46318,https://i.ytimg.com/vi/fAIX12F6958/default.jpg,False,False,False,Every adventure has a beginning. Watch the off...,US
375865,gS1DbvHHVH0,18.14.06,Going in to brain surgery,Simone Giertz,28,2018-05-30T14:22:13.000Z,[none],1635301,120791,1098,20711,https://i.ytimg.com/vi/gS1DbvHHVH0/default.jpg,False,False,False,Weâll post an update on Instagram and Twitte...,US
375873,E4c7EE8_IX0,18.14.06,Weezer - Africa,weezer,10,2018-05-29T12:00:11.000Z,[none],4682557,115240,5069,9170,https://i.ytimg.com/vi/E4c7EE8_IX0/default.jpg,False,False,False,Stream + download the song: http://fanlink.to/...,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US

# 3. For each channel, determine the total number of views

In [5]:
channel_n_views = df.groupby("channel_title", as_index=False)["views"].sum().sort_values("views", ascending=False)

In [6]:
channel_n_views

              channel_title        views
4564    ChildishGambinoVEVO  11016766510
15536  Marvel Entertainment  10430605449
17726            NickyJamTV   9479859505
18466                 Ozuna   8623329509
28412               ibighit   8205572221
...                     ...          ...
17437     NavylittleMonster          365
25828      Videostendencias          302
17837         No Comment TV          284
22560            Sport Life          163
1370      Alexander Redking          153

[37824 rows x 2 columns]

# 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [7]:
excluded_df = df[(df['comments_disabled']) & (df['ratings_disabled']) | (df['video_error_or_removed'])]

In [8]:
df = df.drop(excluded_df.index)
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. BeyoncÃ©,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. BeyoncÃ© ...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO â¶ \n\nSUBSCRIBE âº ...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,ð§: https://ad.gt/yt-perfect\nð°: https://...,CA

In [9]:
df.shape

(373322, 17)

# 5. Add a like_ratio column storing the ratio between the number of likes and dislikes

In [10]:
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. BeyoncÃ©,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. BeyoncÃ© ...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO â¶ \n\nSUBSCRIBE âº ...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,ð§: https://ad.gt/yt-perfect\nð°: https://...,CA

In [11]:
import numpy as np
df["like_ratio"] = np.where(df["dislikes"] > 0, df["likes"] / df["dislikes"], np.nan)
cols = list(df.columns)
cols.insert(cols.index('dislikes') + 1, cols.pop(cols.index('like_ratio')))
df = df[cols]

In [12]:
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,like_ratio,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. BeyoncÃ©,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,18.135076,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. BeyoncÃ© ...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,75.707346,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,27.352500,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO â¶ \n\nSUBSCRIBE âº ...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,66.485168,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,77.513044,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,ð§: https://ad.gt/yt-perfect\nð°: https://...,CA

# 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [19]:
df['publish_time'] = pd.to_datetime(df['publish_time'])
df['publish_time_interval'] = df['publish_time'].dt.floor('10min')

In [20]:
df[['publish_time', 'publish_time_interval']]

                    publish_time     publish_time_interval
0      2017-11-10 17:00:03+00:00 2017-11-10 17:00:00+00:00
1      2017-11-13 17:00:00+00:00 2017-11-13 17:00:00+00:00
2      2017-11-12 19:05:24+00:00 2017-11-12 19:00:00+00:00
3      2017-11-12 18:01:41+00:00 2017-11-12 18:00:00+00:00
4      2017-11-09 11:04:14+00:00 2017-11-09 11:00:00+00:00
...                          ...                       ...
375937 2018-05-18 13:00:04+00:00 2018-05-18 13:00:00+00:00
375938 2018-05-18 01:00:06+00:00 2018-05-18 01:00:00+00:00
375939 2018-05-18 17:34:22+00:00 2018-05-18 17:30:00+00:00
375940 2018-05-17 17:00:04+00:00 2018-05-17 17:00:00+00:00
375941 2018-05-17 17:09:38+00:00 2018-05-17 17:00:00+00:00

[373322 rows x 2 columns]

# 7. For each interval, determine the number of videos, average number of likes and of dislikes.

In [21]:
interval_stats = (df.drop_duplicates(["video_id", "country"]) 
      .groupby("publish_time_interval").agg(num_videos=("video_id", "nunique"),
          avg_likes=("likes", "mean"),avg_dislikes=("dislikes", "mean"),).reset_index())

In [22]:
interval_stats

          publish_time_interval  num_videos  avg_likes  avg_dislikes
0     2006-07-23 08:20:00+00:00           1      459.0         152.0
1     2007-03-05 16:20:00+00:00           1      333.0           2.0
2     2007-06-25 06:50:00+00:00           1      468.0           6.0
3     2007-12-03 20:50:00+00:00           1      112.0           4.0
4     2008-01-07 21:20:00+00:00           1       89.0           2.0
...                         ...         ...        ...           ...
30378 2018-06-14 02:30:00+00:00           1      853.0          77.0
30379 2018-06-14 03:00:00+00:00           2     2304.5          31.5
30380 2018-06-14 03:20:00+00:00           1     1414.0          28.0
30381 2018-06-14 03:30:00+00:00           1     8481.0         252.0
30382 2018-06-14 03:40:00+00:00           1      374.0          24.0

[30383 rows x 4 columns]

# 8. For each tag, determine the number of videos
Notice that tags contains a string with several tags.

In [25]:
df_vid = df.drop_duplicates(["video_id", "country"])
tags_exploded = (df_vid[df_vid["tags"] != "[none]"]["tags"].str.replace('"', '', regex=False)
      .str.split("|").explode().dropna().str.strip())
tag_n_videos = tags_exploded.value_counts().reset_index()
tag_n_videos.columns = ["tag", "num_videos"]

In [26]:
tag_n_videos

                    tag  num_videos
0                  2018        6528
1                 funny        5954
2                comedy        4491
3                  news        3490
4                  2017        3120
...                 ...         ...
841290    PlatinumGames           1
841291      Solid Snake           1
841292            Pichu           1
841293     Ice Climbers           1
841294  the great taste           1

[841295 rows x 2 columns]

# 9. Find the tags with the largest number of videos

In [27]:
popular_tags = tag_n_videos.head(10)

In [28]:
popular_tags

          tag  num_videos
0        2018        6528
1       funny        5954
2      comedy        4491
3        news        3490
4        2017        3120
5       video        2598
6        show        2389
7       humor        2336
8  television        2109
9          tv        2062

# 10. For each (tag, country) pair, compute average ratio likes/dislikes

In [32]:
df_vid = df.drop_duplicates(["video_id", "country"]).copy()
df_vid["like_ratio"] = np.where(df_vid["dislikes"] > 0, df_vid["likes"]/df_vid["dislikes"], np.nan)
df_exploded = df_vid[df_vid["tags"] != "[none]"].copy()
df_exploded["tag"] = (df_exploded["tags"].str.replace('"','', regex=False).str.split("|"))
df_exploded = df_exploded.explode("tag")
df_exploded["tag"] = df_exploded["tag"].astype(str).str.strip()
df_exploded = df_exploded[df_exploded["tag"] != ""]

In [33]:
avg_tag_country = (df_exploded.groupby(["tag","country"])["like_ratio"].mean().reset_index())

In [34]:
avg_tag_country

                                                       tag country  like_ratio
0                                ! Banii i-au luat mintile      DE    6.222739
1                                                       !!      FR   12.452875
2                                                       !!      MX   38.081559
3                                          !! *me bloquea*      MX   65.260870
4                                                      !!!      MX   12.952381
...                                                    ...     ...         ...
1088445                                               ð¥      DE   29.000000
1088446           ð­ #rÃ©sistancelamaindesqueezie â¤ï¸      FR   10.219048
1088447  ð­ÙÙØ² Ø¹Ø³ÙØ±Ù Ø§ÙÙØ­ÙØ¯ Ù
Ù Ø§ÙØ·...      FR    6.223873
1088448                             ð smartpixel.com.ua      RU    0.714286
1088449                    ð¤ ZARBEX zahlt Schutzgeld!!!      DE   13.989691

[1088450 rows x 3 columns]

# 11. For each (trending_date, country) pair, the video with the largest number of views

In [35]:
trending_max_n_views = df.loc[df.groupby(['trending_date', 'country'])['views'].idxmax()]

In [36]:
trending_max_n_views

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,like_ratio,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,publish_time_interval
3398,6ZfuNTqbHE8,17.01.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",56367282,2157741,34078,63.317712,303178,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an ideaâ¦ Avengers: Infinity War. I...,CA,2017-11-29 13:20:00+00:00
44280,6ZfuNTqbHE8,17.01.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",56367282,2157737,34077,63.319453,303178,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an ideaâ¦ Avengers: Infinity War. I...,DE,2017-11-29 13:20:00+00:00
85252,3VbHg5fqBYw,17.01.12,Avengers: Infinity War Trailer Tease,Marvel Entertainment,24,2017-11-28 17:09:22+00:00,"marvel""|""comics""|""comic books""|""nerdy""|""geeky""...",7281189,180808,19955,9.060787,21244,https://i.ytimg.com/vi/3VbHg5fqBYw/default.jpg,False,False,False,Thank you to the best fans in the universe! Ma...,FR,2017-11-28 17:00:00+00:00
126032,TyHvyGVs42U,17.01.12,"Luis Fonsi, Demi Lovato - Ãchame La Culpa",LuisFonsiVEVO,10,2017-11-17 05:00:01+00:00,"Luis|""Fonsi""|""Demi""|""Lovato""|""Ãchame""|""La""|""C...",143408235,2686169,137938,19.473742,144217,https://i.ytimg.com/vi/TyHvyGVs42U/default.jpg,False,False,False,âÃchame La Culpaâ disponible ya en todas ...,GB,2017-11-17 05:00:00+00:00
164617,6ZfuNTqbHE8,17.01.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",56367282,2157733,34077,63.319336,303178,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an ideaâ¦ Avengers: Infinity War. I...,IN,2017-11-29 13:20:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216792,aJOTlE1K90k,18.31.05,Maroon 5 - Girls Like You ft. Cardi B,Maroon5VEVO,10,2018-05-31 04:00:00+00:00,"Maroon|""Girls""|""Like""|""You""|""Interscope""|""Reco...",3057987,406732,4521,89.965052,31301,https://i.ytimg.com/vi/aJOTlE1K90k/default.jpg,False,False,False,Girls Like Youâ is out now.http://smarturl.i...,JP,2018-05-31 04:00:00+00:00
251198,ntWSnDV0MYs,18.31.05,[MV] AOA _ Bingle Bangle(ë¹ê¸ë± ê¸),1theK (ìëì¼ì´),10,2018-05-28 09:00:03+00:00,"Kpop|""1theK""|""ìëì¼ì´""|""loen""|""ë¡ì""|""ë...",4150448,186262,9728,19.146998,15989,https://i.ytimg.com/vi/ntWSnDV0MYs/default.jpg,False,False,False,[MV] AOA _ Bingle Bangle(ë¹ê¸ë± ê¸)*English...,KR,2018-05-28 09:00:00+00:00
291483,xTlNMmZKwpA,18.31.05,"Cardi B, Bad Bunny & J Balvin - I Like It [Off...",Cardi B,10,2018-05-29 14:05:10+00:00,"Cardi B|""I Like It""|""Invasion of Privacy""|""Bad...",20723565,1018817,48091,21.185191,68790,https://i.ytimg.com/vi/xTlNMmZKwpA/default.jpg,False,False,False,"Cardi B, Bad Bunny & J Balvin - I Like It from...",MX,2018-05-29 14:00:00+00:00
332058,1nX0kF2UwDc,18.31.05,[BadComedian] - ÐÐ²Ð¸Ð¶ÐµÐ½Ð¸Ðµ ÐÐ²ÐµÑÑ (Ð...,BadComedian,23,2018-05-30 18:20:48+00:00,"BadComedian|""ÐÐ²Ð³ÐµÐ½""|""Bad""|""Comedian""|""Ð¤Ð...",3125598,334685,7777,43.035232,34556,https://i.ytimg.com/vi/1nX0kF2UwDc/default.jpg,False,False,False,#BadComedian Ð¾Ð±Ð·Ð¾Ñ ÑÐ¸Ð»ÑÐ¼Ð° ÐÐ²Ð¸Ð¶Ð...,RU,2018-05-30 18:20:00+00:00
373139,VYOjWnS4cMY,18.31.05,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07+00:00,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",217750076,4934188,335462,14.708635,509799,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,âThis is Americaâ by Childish Gambino http...,US,2018-05-06 04:00:00+00:00

# 12. Divide trending_date into three columns: year, month, day

In [37]:
df['trending_date'] = pd.to_datetime(df['trending_date'], format='%y.%d.%m')
df['year'] = df['trending_date'].dt.year
df['month'] = df['trending_date'].dt.month
df['day'] = df['trending_date'].dt.day

# 13. For each (month, country) pair, the video with the largest number of views

In [38]:
monthly_max_n_views = df.loc[df.groupby(["month", "country"])["views"].idxmax()]

In [39]:
monthly_max_n_views

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,publish_time_interval,year,month,day
11214,LsoLEjrDogU,2018-01-09,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04 04:49:43+00:00,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",43067983,1717177,61567,...,https://i.ytimg.com/vi/LsoLEjrDogU/default.jpg,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,CA,2018-01-04 04:40:00+00:00,2018,1,9
51930,LsoLEjrDogU,2018-01-08,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04 04:49:43+00:00,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",37728802,1629946,56305,...,https://i.ytimg.com/vi/LsoLEjrDogU/default.jpg,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,DE,2018-01-04 04:40:00+00:00,2018,1,8
92853,LsoLEjrDogU,2018-01-08,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04 04:49:43+00:00,"Bruno Mars""|""Finesse""|""Cardi B""|""Finesse Remix...",37728802,1629948,56305,...,https://i.ytimg.com/vi/LsoLEjrDogU/default.jpg,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,FR,2018-01-04 04:40:00+00:00,2018,1,8
135208,LsoLEjrDogU,2018-01-18,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04 04:49:43+00:00,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",90598955,2248693,93089,...,https://i.ytimg.com/vi/LsoLEjrDogU/default.jpg,False,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,GB,2018-01-04 04:40:00+00:00,2018,1,18
173405,dfnCAmr569k,2018-01-18,"Taylor Swift - End Game ft. Ed Sheeran, Future",TaylorSwiftVEVO,10,2018-01-12 05:00:01+00:00,"Taylor|""Swift""|""End""|""Game""|""Big""|""Machine""|""Pop""",42019590,1804377,100033,...,https://i.ytimg.com/vi/dfnCAmr569k/default.jpg,False,False,False,Music video by Taylor Swift performing End Gam...,IN,2018-01-12 05:00:00+00:00,2018,1,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166769,FlsCjmMhFmw,2017-12-12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",125432237,2912710,1545017,...,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",IN,2017-12-06 17:50:00+00:00,2017,12,12
224092,FlsCjmMhFmw,2017-12-11,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",113876217,2811223,1470388,...,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",KR,2017-12-06 17:50:00+00:00,2017,12,11
259064,FlsCjmMhFmw,2017-12-10,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",100912384,2656698,1353667,...,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",MX,2017-12-06 17:50:00+00:00,2017,12,10
299087,FlsCjmMhFmw,2017-12-08,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",52611730,1891836,884967,...,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",RU,2017-12-06 17:50:00+00:00,2017,12,8
341174,FlsCjmMhFmw,2017-12-14,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",149376127,3093544,1643059,...,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",US,2017-12-06 17:50:00+00:00,2017,12,14

# 14. Read all json files with the video categories

In [40]:
import json
cartella = pl.Path(r"C:\Users\peter_6\Downloads\trendingYT\trendingYT")
dfjs = pd.concat((pd.json_normalize(json.loads(f.read_text(encoding="utf-8"))["items"])
        .assign(country=f.stem.split("_")[0])
                  for f in cartella.glob("*_category_id*.json")), ignore_index=True)
dfjs['id'] = dfjs['id'].astype(int)
dfjs.head()

,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable,country
0,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKm...",1,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True,CA
1,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45Z...",2,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles,True,CA
2,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10,UCBR8-60-B28hp2BmDPdntcQ,Music,True,CA
3,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-o...",15,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True,CA
4,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM...",17,UCBR8-60-B28hp2BmDPdntcQ,Sports,True,CA

In [41]:
dfjs.shape

(311, 7)

# 15. For each country, determine how many videos have a category that is not assignable.

In [42]:
df_merged = pd.merge(df, dfjs,left_on=["category_id", "country"],
    right_on=["id", "country"],how="left")
not_assignable = df_merged[df_merged["snippet.assignable"] == False]
risultato_15 = not_assignable.groupby("country").size()
risultato_15_unique = not_assignable.groupby("country")["video_id"].nunique()

In [43]:
risultato_15_unique

country
CA    111
DE    105
FR    107
GB      1
IN    124
KR     75
MX      3
RU    169
US      4
Name: video_id, dtype: int64